// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import LikertSurveyConcept from "./LikertSurvey/LikertSurveyConcept.ts";
import ListenBrainzAPIConcept from "./ListenBrainzAPI/ListenBrainzAPIConcept.ts";
import MusicBrainzAPIConcept from "./MusicBrainzAPI/MusicBrainzAPIConcept.ts";
import RecommendationConcept from "./Recommendation/RecommendationConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import UserConcept from "./User/UserConcept.ts";

export type { default as LikertSurveyConcept } from "./LikertSurvey/LikertSurveyConcept.ts";
export type { default as ListenBrainzAPIConcept } from "./ListenBrainzAPI/ListenBrainzAPIConcept.ts";
export type { default as MusicBrainzAPIConcept } from "./MusicBrainzAPI/MusicBrainzAPIConcept.ts";
export type { default as RecommendationConcept } from "./Recommendation/RecommendationConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as UserConcept } from "./User/UserConcept.ts";

// Initialize the database connection
export const [db, client] = await testDb();

export const LikertSurvey = Engine.instrumentConcept(new LikertSurveyConcept(db));
export const ListenBrainzAPI = Engine.instrumentConcept(new ListenBrainzAPIConcept(db));
export const MusicBrainzAPI = Engine.instrumentConcept(new MusicBrainzAPIConcept(db));
export const Recommendation = Engine.instrumentConcept(new RecommendationConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const User = Engine.instrumentConcept(new UserConcept(db));
